### ISSUE TITLE
Combining test cases from multiple test suites into one badge

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#182]
in the current architecture the test cases parameters are defined by one templates per test suite, but the actual test case parameter values are only defined once per badge. This needs to be improved, in order to support test case specific parameter settings (and not just test suite specific parameters).

**Comment by ducana** [comment]
Since  each Testsuite has a TcParam.json there is a conflict with the names in the SUT/badge directory. There is also a problem when 2 badges for a Testsuite are made: the Testsuite directory is not specified in the badge and cannot be stored under the badge name. Proposal: add the Testsuite name to the interoperability requirement.

**Comment by ducana** [comment]
This has been made redundant by using interoperability requirements in badges instead of testcases.
