### ISSUE TITLE
IVCT UI does not work behind proxy

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#189]
Minor issue, but I noticed that the IVCT UI does not work work behind a proxy.

Proxy is in this case a Kubernetes nginx Ingress. Proxy maps "/ivct/ivct.gui.ui.html" to "/ivct.gui.ui.html". Login page appears, but logging in fails.

Work around is to access the UI via a published Kubernetes node port.

**Comment by rhzg** [comment]
I think the problem is, that the GUI consists of two parts, a client for handling the UI representation, and a server part for handling the busines logic. 

Your browser will access only the client part via "some.server.org/ivct/ivct.gui.ui.html", but the client part needs to access the server part. And for that access, it needs to know the server name. This is configured in the file 

~~~~
webapps\ivct.gui.ui.html##2.0.1\WEB-INF\classes\config.properties:
....
scout.backendUrl=http://localhost:8080/ivct.gui.server
....
~~~~

and localhost will probably not work inside your kubernetes setup.

**Comment by rhzg** [comment]
could not be replicated - problem propably disappeared
