### ISSUE TITLE
Test Case Results - where to put them?

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#198]
The standard behavior for test cases on creating results is to use the JMS logging feature. Any message created via logger.info (‘some info’) will be shown in the GUI and will be stored within a file below the SuT/Badge folders. 

The question is, do we expect to have any other result files? For historical reasons, some of the HLA-BASE test cases are creating such files. These extra files are currently to shown within the GUI. 

My preference is to have every output within the log message stream – but I would like to hear the options from our test case writers.

**Comment by rmauget** [comment]
The requirement for ETC FRA is to produce some test results files that can be stored as a proof that the tests were performed and that the results were OK.
To me, we must not mix up 2 different kinds of needs about log files:
-	The need to have some log during the execution of the test, to know if the test is running well or if there is a trouble (and so, if some corrections / adjustments have to be made). => This is what I call log
-	The need to have a trace of the results of the test, as a sum up of what happened. Those results must be saved / archived in order to show them if some questions raised long time after the execution of the test => This is what I call results

Of course, the log file can also include the results at its end, just before the test is terminated. But, in that case, only the last part of the log file, the one that content the results, need to be archived, not the overall log file.

**Comment by rhzg** [comment]
This is implemented in the test report feature
