### ISSUE TITLE
Error in Test Case instantiation using Portico composition

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#226]
When I Execute TC hw_iosb ?> HLA-Declaration-2017 > IR-SOM-0003, I get the following error:

````
tc-runner_1               | 2019-08-06 12:00:04,653 : TestEngine:onMessageConsumer:run: trace
tc-runner_1               | 2019-08-06 12:00:04,691 : TestEngine:onMessageConsumer:run: nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check
tc-runner_1               | 2019-08-06 12:00:04,692 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin
tc-runner_1               | 2019-08-06 12:00:04,692 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: setCurrentDirectory true
tc-runner_1               | 2019-08-06 12:00:04,693 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: TC DIR is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin
tc-runner_1               | 2019-08-06 12:00:04,694 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: The test case class is: nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check
logsink_1                 | 2019-08-06 12:00:04,713 LogSink: Test Case changed to :nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check
tc-runner_1               | 2019-08-06 12:00:04,743 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: Test Case Started
tc-runner_1               | 2019-08-06 12:00:04,744 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check:
tc-runner_1               | TEST CASE PARAMETERS -------------------------------------- BEGIN
tc-runner_1               | {"somFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorldSOM.xml"}],"fomFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorld.xml"}],"resultDirectory":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017","testDuration":"60"}
tc-runner_1               | TEST CASE PARAMETERS -------------------------------------- END
tc-runner_1               |
logsink_1                 | 2019-08-06 12:00:04,748 LogSink: 2019-08-06 12:00:04.692+0000: TestEngine:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin
logsink_1                 | 2019-08-06 12:00:04,755 LogSink: 2019-08-06 12:00:04.692+0000: TestEngine:onMessageConsumer:run: setCurrentDirectory true
logsink_1                 | 2019-08-06 12:00:04,759 LogSink: 2019-08-06 12:00:04.693+0000: TestEngine:onMessageConsumer:run: TC DIR is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin
logsink_1                 | 2019-08-06 12:00:04,762 LogSink: 2019-08-06 12:00:04.694+0000: TestEngine:onMessageConsumer:run: The test case class is: nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check
tc-runner_1               | 2019-08-06 12:00:04,762 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: Error while TC instanciation
tc-runner_1               | Exception in thread "Thread-2" java.lang.NullPointerException
tc-runner_1               |     at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:115)
tc-runner_1               |     at de.fraunhofer.iosb.testrunner.TestEngine$TestScheduleRunner.run(TestEngine.java:203)
tc-runner_1               |     at java.lang.Thread.run(Thread.java:748)
````

Compositions:
- IVCT composition (from dev branch): Portico, host mode.
- SUT composition (from dev branch): not used

Runner version:
````
tc-runner_1               | 12:07:40.991 [main] INFO  nato.ivct.commander.Factory - IVCT Version 2.1.0-SNAPSHOT, build v2.0.1-136-g5d7b143
````

**Comment by bergtwvd** [comment]
In the same session, I see the following in the console:

````
tc-runner_1               | 12:11:13.034 [main] INFO  nato.ivct.commander.Factory - IVCT Version 2.1.0-SNAPSHOT, build v2.0.1-136-g5d7b143
tc-runner_1               | 12:11:13.049 [main] DEBUG nato.ivct.commander.Factory - /root/application exists
tc-runner_1               | 12:11:13.050 [main] DEBUG nato.ivct.commander.Factory - /root/application is directory
tc-runner_1               | 12:11:13.052 [main] ERROR nato.ivct.commander.Factory - Unable to read IVCT_CONF = /root/conf/IVCT.properties  creating default values
tc-runner_1               | 12:11:13.067 [main] WARN  nato.ivct.commander.Factory - New IVCT.properties file has been created with default values. Please verify settings!
tc-runner_1               | 12:11:13.070 [main] WARN  nato.ivct.commander.Factory - {}
tc-runner_1               | 12:11:13.070 [main] DEBUG nato.ivct.commander.Factory - Properties used: {}
````

**Comment by rhzg** [comment]
I believe this error is caused by the latest change in the TS_HLA_BASE project (see commit “Remove parameters from TcParam.json files.”) which broke the travis build

Von: bergtwvd <notifications@github.com>
Gesendet: Dienstag, 6. August 2019 14:06
An: IVCTool/IVCT_Framework <IVCT_Framework@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [IVCTool/IVCT_Framework] Error in Test Case instantiation using Portico composition (#226)


When I Execute TC hw_iosb ?> HLA-Declaration-2017 > IR-SOM-0003, I get the following error:

tc-runner_1               | 2019-08-06 12:00:04,653 : TestEngine:onMessageConsumer:run: trace

tc-runner_1               | 2019-08-06 12:00:04,691 : TestEngine:onMessageConsumer:run: nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check

tc-runner_1               | 2019-08-06 12:00:04,692 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin

tc-runner_1               | 2019-08-06 12:00:04,692 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: setCurrentDirectory true

tc-runner_1               | 2019-08-06 12:00:04,693 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: TC DIR is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin

tc-runner_1               | 2019-08-06 12:00:04,694 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: TestEngine:onMessageConsumer:run: The test case class is: nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check

logsink_1                 | 2019-08-06 12:00:04,713 LogSink: Test Case changed to :nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check

tc-runner_1               | 2019-08-06 12:00:04,743 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: Test Case Started

tc-runner_1               | 2019-08-06 12:00:04,744 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check:

tc-runner_1               | TEST CASE PARAMETERS -------------------------------------- BEGIN

tc-runner_1               | {"somFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorldSOM.xml"}],"fomFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorld.xml"}],"resultDirectory":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017","testDuration":"60"}

tc-runner_1               | TEST CASE PARAMETERS -------------------------------------- END

tc-runner_1               |

logsink_1                 | 2019-08-06 12:00:04,748 LogSink: 2019-08-06 12:00:04.692+0000: TestEngine:onMessageConsumer:run: tsRunFolder is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin

logsink_1                 | 2019-08-06 12:00:04,755 LogSink: 2019-08-06 12:00:04.692+0000: TestEngine:onMessageConsumer:run: setCurrentDirectory true

logsink_1                 | 2019-08-06 12:00:04,759 LogSink: 2019-08-06 12:00:04.693+0000: TestEngine:onMessageConsumer:run: TC DIR is /root/conf/TestSuites/TS_HLA_Declaration-2.0.0/bin

logsink_1                 | 2019-08-06 12:00:04,762 LogSink: 2019-08-06 12:00:04.694+0000: TestEngine:onMessageConsumer:run: The test case class is: nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check

tc-runner_1               | 2019-08-06 12:00:04,762 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: Error while TC instanciation

tc-runner_1               | Exception in thread "Thread-2" java.lang.NullPointerException

tc-runner_1               |     at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:115)

tc-runner_1               |     at de.fraunhofer.iosb.testrunner.TestEngine$TestScheduleRunner.run(TestEngine.java:203)

tc-runner_1               |     at java.lang.Thread.run(Thread.java:748)

Compositions:

  *   IVCT composition (from dev branch): Portico, host mode.
  *   SUT composition (from dev branch): not used

**Comment by rhzg** [comment]
fixed
