### ISSUE TITLE
Version check between TC.exec and TC.lib

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#227]
test case engine and library are combined at runtime and may be compiled against different versions. The engine shall check the version of the library used by a test suite against a compatibility matrix.

**Comment by rhzg** [comment]
this feature is implemented in the framework and also integrated into the helloWorld test suite. It still need to be integrated into the HLA_BASE test suite

**Comment by rhzg** [comment]
integrated and tested. Documentation need to be added (@brfkar : could you please add some lines to explain how it work)

**Comment by brfkar** [comment]
### Compile-time-version - Information in the TestCases /TestSuites

While  compile-time  the TestCase,  a specific IVCT-version (and TC.lib) is used. 
This version  should be documented   'in'  the TestCases.
The information is entered manually, before releasing a new version, in the gradle file libraries.gradle . (e.g. ivctVersion = '2.1.1' )
Because at runtime this file libraries.gradle is not present, it will be written by the gradle build process 
in a  property file  "testCaseBuild.properties",   which is found  in the  TestSuite-jar file.
We put the task to write the Version-Information  from libraries.gradle  to  testCaseBuild.properties
in the  TestsuiteName.gradle file in the TestSuite specific folder
If  someone use another build System for TestCases, it would be essential  to pass the version information in another way to  the  testCaseBuild.properties

### Informations about  compatible Versions   in  TestEngine   (available  at runtime)
In the same manner as we documented the IVCT-Version in TestCases, 
the information which Versions of the TC.lib should be compatible to 'this'  version of TestEngine is processed.
A list of compatible versions (array/hasmap) ist written manually in the libraries.gradle  of the IVCT_Framework.

compatibleVersions = ['3.0.0':'compatible','2.2.2-SNAPSHOT':'compatible', '2.1.1':'compatible', '2.1.0':'incompatible']

In TC.exec/TC.exec.gradle a task is defined which writes the informations from the libraries.gradle  to the property-File  compatibleVersions.properties.

### Compare Versions while running a TestCase
As all TestCases are subclasses of  AbstractTestCase (part of  TC.lib),  the method to read  the IVCT-Version-information  at runtime  ist situated  here.  
Thus every TestCase has a method " getIVCTVersion()"  which reads the value for  'ivctVersion'   from  testCaseBuild.properties.
It is the TestEngine which calls for each testcase this method  and uses the gotten String  to create a new  instance of  the class  IVCTVersionCheck.
IVCTVersionCheck  checks  this value against  the list it reads from the compatibleVersions.properties
to  evaluate if the Versions are compatible.
In case of  no  positive match,  it  throw a special exception.

**Comment by rhzg** [comment]
implemented and documented, see https://github.com/IVCTool/IVCT_TestSuiteDevelopment/blob/development/docs/src/3-6_Versioncheck-between-TestCases-and-Runtime-environment.adoc
