### ISSUE TITLE
gradle build does not work out of the box

### ISSUE THREAD

**Issue by PHameete** [IVCTool/IVCT_Framework#97]
running `gradle build` in the IVCT_Framework root folder does not work out of the box because the tests for the Command project require ENV variable IVCT_CONF to be configured.

It would be preferable to include special unit test configuration for these unit tests rather than relying on the configuration at the location indicated by the ENV variable.

**Comment by rhzg** [comment]
we propose to raise a "AssumptionViolatedException" in all JUnit test cases, for situations like the unkonwn environment variable.

**Comment by rhzg** [comment]
the build shall be possible after clone the framework rep in a fresh folder

**Comment by ducana** [comment]
The build can now be completed without any further configuration.
What about gradle test? At the moment, it is necessary to have an ActiveMQ running to be able run all the gradle tests. Does this cause a problem for e.g. Travis?
To adjust the IVCT system so that all the gradle tests work without ActiveMQ is not really desirable since that can hide issues that deal with the calls to ActiveMQ.
Ideally we also need tests that test the communication via ActiveMQ between two or more processes.

Another question is: should the gradle tests work if the environment variables or IVCT.properties have not been adjusted to the local environment e.g IVCT_SUT_HOME_ID with the default value?

**Comment by PHameete** [comment]
Travis can run an ActiveMQ instance in a docker container to allow testing so that's no issue.

I'd say preferably your unit tests are not depending on your 'operational' configuration. They should instead override or use some static testing config.

**Comment by ducana** [comment]
That is good to hear that the automatic tests have no problem.
That means the manual tests can require some extra steps such as starting ActiveMQ before performing the tests. This should be included in issue #93 Testing the Framework. The relevant tests should also display a message that ActiveMQ is required in order to pass the test, then user can quickly see that there is this dependency.

**Comment by PHameete** [comment]
You can run an Embedded Broker for the unit tests that require ActiveMQ:

See for more info:
https://activemq.apache.org/how-to-unit-test-jms-code.html

**Comment by ducana** [comment]
Have added an embedded ActiveMQ for the Junit tests. Some generated Junit frameworks did not work with the embedded ActiveMQ: commented: have commented out some annotations to prevent errors in the Junit tests. After checking out the software, "gradlew build" will have "BUILD SUCCESSFUL".
**NB. "gradlew build" will not work correctly if an external ActiveMQ server is running.**
